version: '3.8' 

services:
  backend:
    build: .           
    container_name: ml_backend_container
    env_file:
      - .env
    ports:
      - "8000:8000"      
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DATA_DIR=/app/data
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=my_user
      - DB_PASSWORD=secret_password
      - DB_PORT=5432
      - REDIS_HOST=redis_db
      - CACHE_MAX_ITEMS=25
      - MIN_VOTES=50
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./models:/app/models
      - ./tests:/app/tests
    depends_on:
      db:
        condition: service_healthy
  frontend:
      container_name: ml_frontend_container
      build:
        context: .
        dockerfile: Dockerfile.frontend
      ports:
        - "8501:8501" 
      environment:
        - API_URL=http://backend:8000
        - TMDB_API_KEY=${TMDB_API_KEY} #klucz API do stronki z grafikami filmów
      depends_on:
        - backend
      volumes:
        - ./src:/app/src


  db:          
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=secret_password
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis_db:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  prometheus: #do monitorowania zachowania modelu
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - backend

  grafana: #do monitoringu Prometheusa
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Hasło do logowania
    depends_on:
      - prometheus

volumes:
  postgres_data:
