FROM --platform=arm64 python:3.11-slim
WORKDIR /app
RUN pip install streamlit requests
COPY src/ /app/src/
EXPOSE 8501
CMD ["streamlit", "run", "src/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]